environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: stable
branches:
  only:
    - master

clone_depth: 50

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        Start-FileDownload "$url/Install%20MultiRust.ps1" -FileName "Install MultiRust.ps1"
        Start-FileDownload "$url/Build.ps1" -FileName "Build.ps1"
        Start-FileDownload "$url/Run%20Tests%20and%20Clippy.ps1" -FileName "Run Tests and Clippy.ps1"
        . ".\Install MultiRust.ps1"

platform:
  - x86
  - x64

configuration:
#  - Debug
  - Release

build_script:
  - ps: . ".\Build.ps1"

test_script:
  - ps: . ".\Run Tests and Clippy.ps1"
